apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: voip
  labels:
    component: nats
spec:
  selector:
    component: nats
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
